-- CreateEnum
CREATE TYPE "Role" AS ENUM ('MERCHANT', 'TRANSPORTER');

-- CreateEnum
CREATE TYPE "BidStatus" AS ENUM ('OPEN', 'ASSIGNED', 'CLOSED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "SubmissionStatus" AS ENUM ('PENDING', 'ACCEPTED', 'REJECTED');

-- AlterTable
ALTER TABLE "User"
ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "role" TYPE "Role" USING UPPER("role")::"Role";

-- AlterTable
ALTER TABLE "Bid"
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "status" TYPE "BidStatus" USING UPPER("status")::"BidStatus";

-- AlterTable
ALTER TABLE "BidSubmission"
ALTER COLUMN "status" TYPE "SubmissionStatus" USING UPPER("status")::"SubmissionStatus";